image: bradrydzewski/node:0.10
env: 
script:
  - echo $PATH
  - echo `which npm`
  - npm -v
  - npm install -g grunt-cli bower
  - echo "grunt version:"
  - grunt --version
  - echo "bower version:"
  - bower -v
  - npm install
  - bower install
  - grunt build
notify:
  email:
     recipients:
       - rbkreisberg@gmail.com
deploy:
  ssh:
    target: www@apollo.systembiology.net:/local/vis/webapps/scorch
    artifacts: dist/
