image: bradrydzewski/node:0.10
env: 
script:
  - echo `which npm`
  - npm -v
  - npm install -g grunt-cli bower
  - echo "grunt version:"
  - grunt --version
  - echo "bower version:"
  - bower -v
  - bower install
  - grunt build
notify:
  email:
     recipients:
       - rbkreisberg@gmail.com
